### ISSUE TITLE
Unknown CMake command CPMAddPackage

### ISSUE THREAD

**Issue by Mailaender** [vittorioromeo/SSVOpenHexagon#370]
I tried to package 2.0.6 for @openSUSE, but the build system is broken:

```
CMake Error at CMakeLists.txt:57 (CPMAddPackage):
   Unknown CMake command "CPMAddPackage".
```

How do I not make it download during the build?

**Comment by Morxemplum** [comment]
Hi! Due to @vittorioromeo updating the SFML version of the game to SFML 3, an upcoming version of SFML, trying to build the master branch at the moment will lead to build errors. 

Try to clone and build on the current branch `develop` and see if this fixes your problem.

**Comment by her001** [comment]
The error you are seeing definitely is not caused by SFML versions.

1. If you are trying to build off the v2.0.6 tag, that doesn't include the SFML changes.
1. The error is with the [CPMAddPackage command](https://github.com/vittorioromeo/SSVOpenHexagon/blob/2.0.6/CMakeLists.txt#L57) in CMake, not an SFML build-related error.

Not sure why it isn't working, though. [CPM.cmake](https://github.com/cpm-cmake/CPM.cmake#adding-cpm) should be [downloaded and included earlier in the `CMakeLists.txt` file](https://github.com/vittorioromeo/SSVOpenHexagon/blob/2.0.6/CMakeLists.txt#L32-L46).

What version of CMake are you using?

**Comment by Mailaender** [comment]
@openSUSE has that disabled on purpose as downloading during the build is forbidden.
